### PR TITLE
Add MathCrypto

### PR DESCRIPTION
**Pull request by MathCryptoDoc**

### CODE REVIEW

**Comment by MathCryptoDoc** [comment]
https://kusama.subscan.io/extrinsic/16776292-7

**Review by stepanLav — APPROVED** [review]

**Comment by antonkhvorov** [comment]
@MathCryptoDoc are you sure that you don't want to be displayed as Organization (instead of Individual)?

**Comment by stepanLav** [comment]
Thank you for your request!
@MathCryptoDoc 

You can check how it will look like:

<details>
  <summary>App screens</summary>

Screenshot 2023-03-01 at 13 18 18

Screenshot 2023-03-01 at 13 18 22

Screenshot 2023-03-01 at 13 18 25

</details>

**Comment by bart-vde** [comment]
> @MathCryptoDoc are you sure that you don't want to be displayed as Organization (instead of Individual)?

Thanks for the suggestion, but no, you can keep it as Individual. Thanks!

**Comment by MathCryptoDoc** [comment]
> @MathCryptoDoc are you sure that you don't want to be displayed as Organization (instead of Individual)?

Thanks for the suggestion, but no, keep it as is.

**Pull request merged**
