### PR TITLE
Added CoinStudio

### PR DESCRIPTION
**Pull request by CoinStudioDOT**

### CODE REVIEW

**Comment by CoinStudioDOT** [comment]
https://kusama.subscan.io/extrinsic/16776261-2

**Review by stepanLav — APPROVED** [review]

**Comment by stepanLav** [comment]
Thank you for your request!
@CoinStudioDOT 

You can check how it will look like:

<details>
  <summary>App screens</summary>

Screenshot 2023-03-01 at 12 31 35

Screenshot 2023-03-01 at 12 31 51

</details>

**Comment by CoinStudioDOT** [comment]
Thanks for the approval. Preview screens look great! Thanks to Leemo for introducing this feature to me.

**Comment by antonkhvorov** [comment]
Hey @CoinStudioDOT are you sure you don't want to be displayed as Organization?

**Comment by CoinStudioDOT** [comment]
Hey @antonkhvorov I am not sure if Organization would be a correct description. Unless you have envisioned that Validators are recognized as organizations?

**Pull request merged**
