### PR TITLE
Adding Paradox metadata

### PR DESCRIPTION
**Pull request by paradox-tt**
Adding metadata for my profile on Nova's OpenGov delegation screen.

### CODE REVIEW

**Comment by stepanLav** [comment]
Hello! @paradox-tt
Thank you for your submission! We are still work on the workflow regarding that repo, soon it will be completed with all requirements and clear instructions how to submit your changes.  - https://github.com/nova-wallet/opengov-delegate-registry/pull/6

The most important part that all information must be proofed by on-chain operation in terms to avoid fraud. We decided that system.remark with github account and PR number is fit, soon wiki with all step will be available.

### If you want to do it early, you can perform that steps:

1. Get hex representation for string `"$githibUserName:$pullRequestId"` in your case it is "paradox-tt:7".
2. Submit `system.remark("$hex_string")` in Kusama network from account: `HqRcfhH8VXMhuCk5JXe28WMgDDuW9MVDVNofe1nnTcefVZn`.
3. Attach link to that transaction in block explorer to comments of that PR and ping me.

After that we will check it, test your data in our app and if everything is good - approve that PR.

NOTE:
To get hexadecimal representation you can use any convenient way, for example Python script to do that:
```python
def encode_text_to_hex(text):
    hex_str = text.encode('utf-8').hex()

    return '0x' + hex_str

def decode_hex_to_text(hex_str):
    encoded_text = bytes.fromhex(hex_str.replace('0x', ''))
    decoded_text = encoded_text.decode()

    return decoded_text

enode_string = encode_text_to_hex("paradox-tt:7")
print('Prefixed hex: ' + enode_string)
print('Decoded data: ' + decode_hex_to_text(enode_string))
```

**Comment by stepanLav** [comment]
It is how it will looks like in the app:

<details>
  <summary>Screens</summary>

Screenshot 2023-02-09 at 10 02 45

Screenshot 2023-02-09 at 10 02 47

Screenshot 2023-02-09 at 10 02 50


</details>

**Comment by paradox-tt** [comment]
Thank you for the detailed response.  It was very helpful.

Please find verification below:
https://kusama.subscan.io/extrinsic/0x2c7d190234deb85e9b42613da084bb1e0b8dac378f058f3da1db854ca0466c54

**Review by stepanLav — APPROVED** [review]

**Review by valentunn — APPROVED** [review]

**Comment by antonkhvorov** [comment]
Congratulations @paradox-tt on being first person who successfully added their metadata to Nova Wallet Agile Delegations registry 🎉

**Comment by paradox-tt** [comment]
Thanks, it was pretty easy and @stepanLav was very clear with further instructions.

When does this go live? The version of my Nova wallet is v.5.2.0-market  from the demo I think this would be available as part of v5.3.0?

I'm going to market this a lot ;D

**Comment by antonkhvorov** [comment]
We are aiming to finalize the rest of the features (Edit, Revoke delegations) + polish & publish the release on around 22nd of February. Would really appreciate if people would submit the metadata about themselves, especially with some creativity!

Don't forget that "longDescription" is basically a markdown text, so you can be creative and use images/videos/any markdown formatting there

**Review by Emisio1 — APPROVED** [review]

**Pull request merged**
