### PR TITLE
Add stake.plus to the registry

### PR DESCRIPTION
**Pull request by senseless**

### CODE REVIEW

**Comment by stepanLav** [comment]
Hello @senseless!
Thank you for opening PR, could you proof that you have access from this account by following our [instructions](https://docs.novawallet.io/nova-wallet-wiki/governance/add-delegate-information), please?

**Comment by stepanLav** [comment]
@CoinStudioDOT 

You can check how it will look like:

<details>
  <summary>App screens</summary>

Screenshot 2023-03-01 at 12 31 30
Screenshot 2023-03-01 at 12 31 46


</details>

**Comment by senseless** [comment]
Ah, the remark? Sorry I completely missed that.

**Comment by stepanLav** [comment]
> Ah, the remark? Sorry I completely missed that.

Yes, no worries, we have just recently merged the [README.md](../#readme) file, where it is described. If you like how your organisation look like, we will merge your request after checking the transaction

**Review by stepanLav — APPROVED** [review]

**Pull request merged**
