### PR TITLE
markdown format for ChaosDAO description

### PR DESCRIPTION
**Pull request by spazcoin**
restructure ChaosDAO description now that we can see that Anton's description uses Markdown format.

Instead of describing our internal voting process in detail, I've left that detail in the link to our gitbook docs (so it's easy for us to update in the future).

### CODE REVIEW

**Comment by spazcoin** [comment]
two questions:
1) can an animated .svg logo be rendered in the Nova delegation UI, or only a static png/jpeg?
2) Can the "image" link to a logo in our own repo, or must the image reside within this repo?  (https://github.com/ChaosDAO-org/ChaosDAO_docs/raw/main/.gitbook/assets/ChaosDAO_logo.png)

**Review by bLd75 — COMMENTED** [review]
lgtm

**Comment by stepanLav** [comment]
Hello! @spazcoin
Sorry for the long reply, we are still work on the workflow regarding that repo.

> 1. can we provide an animated logo? (maybe .svg, webp, gif?) Can the Nova delegation UI render an animated logo, or only a static png/jpeg?
- No, Nova Wallet can't operate with animated source, moreover we will limit image format in terms to avoid problems in different platforms (iOS/Android) and different devices.

> 2. Can the "image" link to a logo in our own repo, or must the image reside within this Nova repo? (link I would use: https://github.com/ChaosDAO-org/ChaosDAO_docs/raw/main/.gitbook/assets/ChaosDAO_logo.png)
- No, unfortunately it is forbidden too , as we want to control which image will be shown in the app to avoid unexpected behaviour. All images should be downloaded in [repo](https://github.com/nova-wallet/opengov-delegate-registry/tree/master/images)

Soon we will complete all requirements for that information and provide clear instructions to submit your changes.  - https://github.com/nova-wallet/opengov-delegate-registry/pull/6

**Comment by stepanLav** [comment]
Also, your changes in the app will looks like:

<details>
  <summary>Screens</summary>

Screenshot 2023-02-09 at 08 56 35

Screenshot 2023-02-09 at 08 44 30


</details>

**Comment by spazcoin** [comment]
@stepanLav thanks for the info! 
Then this PR is ready for you to merge.

**Comment by Leemo94** [comment]
Here is a system remark "spazcoin:5" from the Any Proxy for the ChaosDAO Referendum Commission Pure Proxy account: https://kusama.subscan.io/extrinsic/16676009-4

**Review by valentunn — APPROVED** [review]

**Pull request merged**
